server:
  port: 10500

spring:
  r2dbc:
    url: ${env.DB_URL}
    username: ${env.DB_USER_NAME}
    password: ${env.DB_PASSWORD}
    pool:
      max-size: 100
      validation-query: SELECT 1
      initial-size: 5
      max-idle-time: 10s
      max-create-connection-time: 2s
      max-acquire-time: 2s
      max-life-time: 3s


logging:
  level:
    org.springframework.r2dbc.core: debug
    org.springframework.web: debug