server:
  port: 10500

datasource:
  config:
    url: ${env.DB_URL}
    username: ${env.DB_USER_NAME}
    password: ${env.DB_PASSWORD}
    max-size: 20
    max-lifetime: 30m
    max-idletime: 20s
    validation-timeout: 5s
    connect-timeout: 5s

logging:
  level:
    org.springframework.r2dbc.core: debug
    org.springframework.web: debug